spark.sql.session.timeZone = Asia/Tehran
spark.shuffle.service.enabled = false
spark.memory.fraction = 0.6
spark.memory.storageFraction = 0.5
spark.dynamicAllocation.enabled = False
spark.sql.autoBroadcastJoinThreshold = 50m
spark.sql.adaptive.enabled = False
spark.sql.adaptive.coalescePartitions.enabled = True
spark.sql.adaptive.skewJoin.enabled = True
spark.shuffle.compress = True
spark.shuffle.spill.compress = True
spark.rdd.compress = True
spark.sql.ansi.enabled = False